# Generated by Django 5.0.6 on 2024-08-03 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('vehiculo', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'entregador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Registros_Pedidos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_responsable', models.CharField(max_length=100, null=True)),
                ('tipo_registro', models.CharField(blank=True, choices=[('ER', 'Eliminacion registro'), ('CR', 'Creacion registro'), ('MR', 'Modificacion registro'), ('NR', 'Nuevo registro'), ('AC', 'Actualizacion comentario'), ('NC', 'Nuevo comentario'), ('AR', 'Actualizacion registro')], max_length=50, null=True)),
                ('hora_registro', models.DateTimeField(auto_now_add=True)),
                ('descripcion_registro', models.CharField(max_length=250, null=True)),
                ('numero_documento', models.ForeignKey(blank=True, db_column='documento', null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.entregador')),
            ],
            options={
                'db_table': 'registros_pedidos',
                'managed': True,
            },
        ),
    ]
