# Generated by Django 5.0.6 on 2024-08-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rename_numero_documento_registros_pedidos_documento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'managed': False},
        ),
    ]
